name: clockapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.6.0' 

dependencies:
  flutter:
    sdk: flutter
  alarm: ^4.1.1
  permission_handler: ^11.4.0
  flutter_expandable_fab: ^2.3.0
  path_provider: ^2.1.5
  mdi: ^5.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data.json
